version: '3.9'
services:
  dind:
    image: docker:dind
    container_name: dind
    restart: unless-stopped
    privileged: true
    environment: 
      - DOCKER_TLS_CERTDIR=/certs
    volumes: 
      - dind-certs-ca:/certs/ca
      - dind-certs-client:/certs/client
    networks: 
      dind:
        aliases:
          - docker
  client:
    build: client
    environment: 
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - dind-certs-client:/certs/client
    command: ['pull', 'busybox']
    networks:
     dind:
    depends_on: 
      - dind
volumes:
  dind-certs-ca:
  dind-certs-client:
networks:
  dind: